version: '3'
services:
  pacs:
    container_name: 'orthanc'
    image: 'jodogne/orthanc-plugins:1.11.0'
    #ports:
      #- '4242:4242/tcp'
      #- '8042:8042/tcp'
    expose:
      - '8042/tcp'
      - '4242/tcp'
    volumes:
      - './orthanc.json:/etc/orthanc/orthanc.json:ro'
      - 'data_pacs:/var/lib/orthanc/db:rw'
  rp:
    container_name: 'caddy'
    image: 'caddy:2.5.1'
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile:ro'
      - 'data_rp:/data:rw'
volumes:
  data_pacs:
  data_rp:

